apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikubeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikubeapp
  template:
    metadata:
      labels:
        app: minikubeapp
    spec:
      containers:
      - name: minikubeapp
        image: jaintushar2001/minikubeapp:version1  
        ports:
        - containerPort: 8000
        resources:                                  
          requests:
            memory: "256Mi"                         
            cpu: "500m"                             
          limits:
            memory: "512Mi"                        
            cpu: "1"      